### ISSUE TITLE
Where to find unaligned ShapeNetCore shapes?

### ISSUE THREAD

**Issue by Steve-Tod** [NVlabs/6dof-graspnet#13]
Hi there, thank you for sharing your code!

Now I'm trying to generate the dataset. However, due to the dependency issue, I'm not able to use your visualizer. So I wrote the visualization code by myself.

However, in visualization, I found some objects look OK, but some objects are too small, or the grasps are always colliding with the objects. The good shapes are from ShapeNetSem and the others are from ShapeNetCore.

I think the problem might be that, in ShapeNetCore, the shapes and centered and normalized. So I'm guessing you were using the unaligned shapes. 

Where do you find these unaligned ShapeNetCore shapes? It would be great if you can directly provide your stl files of ShapeNet objects.

**Comment by clemense** [comment]
Did you close this on purpose?  Unfortunately, we can't share any mesh data. The meshes that were used are from ShapeNet**Sem**, *not* ShapeNet**Core**.
