### ISSUE TITLE
code for grasp evaluation?

### ISSUE THREAD

**Issue by tasbolat1** [NVlabs/6dof-graspnet#22]
Hello @ arsalan-mousavian ,

is there any way we can get some code snippet for grasp evaluation? at least can yotu direct us how to make it work? It is suppose to be in flex and perform shaking action with object grasped by a robot.

**Comment by arsalan-mousavian** [comment]
Unfortunately at this point, we are not able to release the flex code. Hopefully, we will release an isaac gym version of it at some point.

**Comment by tasbolat1** [comment]
@arsalan-mousavian thanks for quick reply.
Can you give an estimated date for issac gym version?
