### ISSUE TITLE
Grasp data size does not match to what paper says

### ISSUE THREAD

**Issue by tasbolat1** [NVlabs/6dof-graspnet#23]
Hi @arsalan-mousavian ,
After getting data from ShapeNet, we end up having 126 objects with 5 categories (box, cylinder, bowls, mugs and bottles). However, paper says 6 categories and 206 objects. Can you clarify how do we get those data?

**Comment by arsalan-mousavian** [comment]
I just double checked the internal version of dataset and it has 126 objects with 5 categories as you said. thanks for pointing out the the error in dataset description.

I highly recommend checking acronym dataset which has significantly more meshes and grasps: https://sites.google.com/nvidia.com/graspdataset

We also released the models trained on ACRONYM dataset which gives better performance.
