### ISSUE TITLE
Unable to access the dataset

### ISSUE THREAD

**Issue by maheshreddy24** [NVlabs/6dof-graspnet#29]
Hey, I was trying to implement the repository but the access to the dataset is denied

**Comment by clemense** [comment]
The dataset link is shown here:   https://github.com/NVlabs/acronym (the link changed recently)

**Comment by maheshreddy24** [comment]
> The dataset link is shown here: https://github.com/NVlabs/acronym (the link changed recently)

Hey what about the checkpoints?

**Comment by arsalan-mousavian** [comment]
I just updated the checkpoints links as well.
