### ISSUE TITLE
InvalidArgumentError:  Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. 

### ISSUE THREAD

**Issue by saadehmd** [NVlabs/6dof-graspnet#4]
Hi, 
I followed all the installation and setup instructions precisely. Downloaded the checkpoint files in 6DoF graspnet/checkpoints  folder and tried running the demo files with all the three args provided in the instructions. But the error is pretty much the same. The traceback looks like this :-

Caused by op u'evaluator/ssg-layer1/FarthestPointSample', defined at:
  File "/home/ahmad3/anaconda2/envs/graspnet/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/ahmad3/anaconda2/envs/graspnet/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ahmad3/6dof-graspnet/demo/main.py", line 152, in <module>
    main(sys.argv[1:])
  File "/home/ahmad3/6dof-graspnet/demo/main.py", line 106, in main
    estimator.build_network()
  File "grasp_estimator.py", line 157, in build_network
    build_evaluator_ops(self._data_dict, self._cfg)
  File "train.py", line 354, in build_evaluator_ops
    gripper_pc_latent=gripper_pc_latent)
  File "models/model.py", line 216, in evaluator_model
    scale)  # Get features of the pc
  File "models/model.py", line 48, in base_network
    64 * scale, 64 * scale, 128 * scale], mlp2=None, group_all=False, is_training=is_training, bn_decay=bn_decay, scope='ssg-layer1')
  File "models/../../pointnet2/utils/pointnet_util.py", line 113, in pointnet_sa_module
    new_xyz, new_points, idx, grouped_xyz = sample_and_group(npoint, radius, nsample, xyz, points, knn, use_xyz)
  File "models/../../pointnet2/utils/pointnet_util.py", line 40, in sample_and_group
    new_xyz = gather_point(xyz, farthest_point_sample(npoint, xyz)) # (batch_size, npoint, 3)
  File "/home/ahmad3/pointnet2/tf_ops/sampling/tf_sampling.py", line 56, in farthest_point_sample
    return sampling_module.farthest_point_sample(inp, npoint)
  File "<string>", line 103, in farthest_point_sample
  File "/home/ahmad3/anaconda2/envs/graspnet/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/ahmad3/anaconda2/envs/graspnet/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/ahmad3/anaconda2/envs/graspnet/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/ahmad3/anaconda2/envs/graspnet/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

No OpKernel was registered to support Op 'FarthestPointSample' with these attrs.  Registered devices: [CPU,XLA_CPU,XLA_GPU], Registered kernels:
  device='GPU'

	 [[node evaluator/ssg-layer1/FarthestPointSample (defined at <string>:103)  = FarthestPointSample[npoint=128](evaluator/concat)]]

Usually whenever there's a size mismatch between the restored graph and the network it shows those mismatched dims something like " The input tensor is (x,x,x,x) and can't restore a tensor of sze (y,y,y,y). But this looks strange. am i missing something in my installation requirements? do i need to setup something more than just the checkpoints file?

**Comment by arsalan-mousavian** [comment]
I think I saw this issue before. Restarting your machine should fix it. Give it a try and let me know if you see the issue again.

I think it has something to do with how the ops are built and added to tensorflow. This is related to the ops built from pointnet++.

**Comment by arsalan-mousavian** [comment]
If restarting did not help and you only have 1 gpu on your machine, you can set this line to 0: 
https://github.com/NVlabs/6dof-graspnet/blob/master/grasp_estimator.py#L74

I will fix it soon.

**Comment by saadehmd** [comment]
Thanks a lot. You were right. it was the wrong gpu ID causing the problem. But after resolving that i have a new one :D 

UnknownError (see above for traceback): Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node vae/decoder/ssg-layer1/conv0/Conv2D (defined at models/../../pointnet2/utils/tf_util.py:173)  = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](vae/decoder/ssg-layer1/conv0/Conv2D-0-TransposeNHWCToNCHW-LayoutOptimizer, vae/decoder/ssg-layer1/conv0/weights/read/_189)]]
	 [[{{node vae/decoder/concat_1/_241}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_380_vae/decoder/concat_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

the warning that this points to is i guess this one:

2020-03-12 09:50:18.216014: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2020-03-12 09:50:18.220303: E tensorflow/stream_executor/cuda/cuda_dnn.cc:373] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR

**Comment by saadehmd** [comment]
going through these 

https://github.com/tensorflow/tensorflow/issues/24828
https://devtalk.nvidia.com/default/topic/1043867/failed-to-get-convolution-algorithm-this-is-probably-because-cudnn-failed-to-initialize

there's an incompatibility between tensorflow>1.8 and recent cuda and cudNN versions.
I'm using cuda-10. and cudnn-7.6.5. Do you recommend doing ?:

pip install --upgrade tensorflow-gpu==1.8.0

**Comment by arsalan-mousavian** [comment]
In README, I put tenorflow 1.12, CUDA 10.0, and CUDNN 7.1.2 on Ubuntu 16.04 as the environment we tested the code. You may want to use the same environment. 

I have also seen the issue with the new cudnn on ubuntu 18.04. I bypassed it by changing the [session creation](https://github.com/NVlabs/6dof-graspnet/blob/master/demo/main.py#L105) using:
```shell
    config = tf.ConfigProto()
    config.gpu_options.allow_growth = True
    sess = tf.Session(config=config)
```
Let me know if it fixes all the issues so that I update the repo.

**Comment by saadehmd** [comment]
Now it's OutOfMemory error all along.

i have tried going as low as : 
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.25)
config=tf.ConfigProto(gpu_options=gpu_options)
config.gpu_options.allow_growth = True
sess = tf.Session(config=config)


but i think it's time i need to find some better hardware resources :D
Thanks for urgent help btw!!

Just as a side note i am running this on Nvidia Quadro t1000 which is kind of consumer grade GPU with just 4GB memory and no tensor/RT cores

**Comment by arsalan-mousavian** [comment]
You need to upgrade your GPU.

You can see the results with fewer samples, which obviously degrades performance, by changing num_samples to 50 for example: https://github.com/NVlabs/6dof-graspnet/blob/master/grasp_estimator.py#L79

and I think you need to remove `gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.25)`

**Comment by jsll** [comment]
@saadehmd 

> Now it's OutOfMemory error all along.
> 
> i have tried going as low as :
> gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.25)
> config=tf.ConfigProto(gpu_options=gpu_options)
> config.gpu_options.allow_growth = True
> sess = tf.Session(config=config)
> 
> but i think it's time i need to find some better hardware resources :D
> Thanks for urgent help btw!!
> 
> Just as a side note i am running this on Nvidia Quadro t1000 which is kind of consumer grade GPU with just 4GB memory and no tensor/RT cores

I got the same error and fixed it by reducing the number of grasps it samples. Try add      cfg["num_samples"] = 50 after cfg['num_refine_steps'] = 10 in demo/main.py and see if it works.

**Comment by jsll** [comment]
@saadehmd 

> Now it's OutOfMemory error all along.
> 
> i have tried going as low as :
> gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.25)
> config=tf.ConfigProto(gpu_options=gpu_options)
> config.gpu_options.allow_growth = True
> sess = tf.Session(config=config)
> 
> but i think it's time i need to find some better hardware resources :D
> Thanks for urgent help btw!!
> 
> Just as a side note i am running this on Nvidia Quadro t1000 which is kind of consumer grade GPU with just 4GB memory and no tensor/RT cores

I got the same error and fixed it by reducing the number of grasps it samples. Try add      cfg["num_samples"] = 50 after cfg['num_refine_steps'] = 10 in demo/main.py and see if it works.
