### ISSUE TITLE
Remove surface or not for evaluation

### ISSUE THREAD

**Issue by seann999** [NVlabs/6dof-graspnet#5]
Should I remove the surface/table points from the point cloud before inputting, or is foreground segmentation not necessary for this model?

**Comment by arsalan-mousavian** [comment]
as mentioned both in the paper and also in the npy files for demo, you need to segment the object of interest. 

For single object you can just do plane removal. For multiple object, you can use any instance segmentation method. We used the [instance segmentation code](https://github.com/chrisdxie/uois) for this [video](https://www.youtube.com/watch?v=jypErPo47IA&feature=emb_title)
