### ISSUE TITLE
Grasp Coordinate Frame Convention

### ISSUE THREAD

**Issue by c-keil** [NVlabs/6dof-graspnet#8]
For comparison/implementation purposes it would be useful to know the convention for conversion between the grasp poses output by graspnet, and a frame on the real robot. At present I have been assuming that the grasp pose is coincident with the hand coordinate frame in ROS. Is that correct? Below is a visualization of that frame in RVIZ. It would also be convenient if a figure could be released specifying the general dimensions of the fingers and coordinate frames to ensure comparisons are done accurately.

![gripper_frame](https://user-images.githubusercontent.com/48033174/82262920-d38d8000-992f-11ea-9dcd-b3dfa3ad45ff.png)

**Comment by clemense** [comment]
Hi,
The finger dimensions are exactly as in the Franka Panda gripper shown above.
The coordinate frame of the trained model should be as shown in this diagram:
![Screenshot from 2020-05-20 00-02-38](https://user-images.githubusercontent.com/1800546/82415831-f2723c00-9a2d-11ea-8e1a-93f8ad7defde.png)
(The origin is the same as in the model above, but the orientation is rotated by -90 degrees around the positive z-axis)

**Comment by arsalan-mousavian** [comment]
Also, you can use `show_gripper_mesh` argument of [draw_scene](https://github.com/NVlabs/6dof-graspnet/blob/master/visualization_utils.py#L41) to visualize the 3D mesh of the grasp to make sure what you get in ROS is similar to the rendering with draw_scene.

In addition, we rendered gripper mesh as marker on the point cloud of camera in rviz to make sure all the transformation + calibration are decent. it helped a lot with catching small transformation bugs.
